import React, { useEffect, useRef, useState } from 'react'

// Simple LED matrix preview for .bin files generated by backend
// .bin format: [0xAA55][2 bytes frameCount LE][1 byte fps][frames RGB data]

async function fetchBin(url: string): Promise<{ fps: number; frames: Uint8Array[] }> {
  const resp = await fetch(url)
  const buf = await resp.arrayBuffer()
  const data = new DataView(buf)
  const magic = data.getUint16(0, true)
  if (magic !== 0xAA55) throw new Error('Invalid BIN header')
  const frameCount = data.getUint16(2, true)
  const fps = data.getUint8(4)
  const pixels = new Uint8Array(buf, 5)
  const size = 768 * 768 * 3
  const frames: Uint8Array[] = []
  for (let i = 0; i < frameCount; i++) {
    const start = i * size
    const end = start + size
    frames.push(pixels.slice(start, end))
  }
  return { fps, frames }
}

function drawFrame(ctx: CanvasRenderingContext2D, rgb: Uint8Array) {
  const size = 768
  const imageData = ctx.createImageData(size, size)
  for (let i = 0, p = 0; i < rgb.length; i += 3, p += 4) {
    imageData.data[p] = rgb[i]
    imageData.data[p + 1] = rgb[i + 1]
    imageData.data[p + 2] = rgb[i + 2]
    imageData.data[p + 3] = 255
  }
  ctx.putImageData(imageData, 0, 0)
}

export default function LEDPreview({ files, fpsOverride }: { files: string[]; fpsOverride?: number }) {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const [loaded, setLoaded] = useState<any[]>([])
  const [playing, setPlaying] = useState<boolean>(false)
  const [loop, setLoop] = useState<boolean>(() => localStorage.getItem('loop') === 'true')
  const [index, setIndex] = useState<number>(0)

  useEffect(() => { localStorage.setItem('loop', loop ? 'true' : 'false') }, [loop])

  useEffect(() => {
    let alive = true
    const loadAll = async () => {
      try {
        const loadedAll = await Promise.all(files.map(f => fetchBin(f)))
        if (!alive) return
        setLoaded(loadedAll)
      } catch (e) {
        console.error(e)
      }
    }
    if (files.length) loadAll()
    return () => { alive = false }
  }, [files.join('|')])

  useEffect(() => {
    let timer: any
    const play = async () => {
      const canvas = canvasRef.current
      if (!canvas) return
      const ctx = canvas.getContext('2d')
      if (!ctx) return
      if (!loaded.length) return

      let current = 0
      const file = loaded[index % loaded.length]
      const fps = fpsOverride || file.fps || 24
      const interval = 1000 / fps

      const tick = () => {
        if (!playing) return
        const frame = file.frames[current]
        if (frame) drawFrame(ctx, frame)
        current += 1
        if (current >= file.frames.length) {
          if (loop || index < loaded.length - 1) {
            current = 0
            if (!loop) setIndex(i => (i + 1) % loaded.length)
          } else {
            setPlaying(false)
            return
          }
        }
        timer = setTimeout(tick, interval)
      }
      timer = setTimeout(tick, interval)
    }
    if (playing) play()
    return () => clearTimeout(timer)
  }, [playing, loaded, index, loop, fpsOverride])

  return (
    <div className="space-y-3">
      <div className="flex items-center gap-2 text-sm">
        <button className="bg-neutral-800 px-3 py-1 rounded" onClick={()=>setPlaying(true)} title="Play All">▶</button>
        <button className="bg-neutral-800 px-3 py-1 rounded" onClick={()=>setPlaying(false)} title="Pause">⏸</button>
        <button className="bg-neutral-800 px-3 py-1 rounded" onClick={()=>{ setIndex(0); setPlaying(false) }} title="Stop">⏹</button>
        <label className="ml-2 flex items-center gap-2" title="Auto-loop playback">
          <input type="checkbox" checked={loop} onChange={e=>setLoop(e.target.checked)} /> 🔁 Loop
        </label>
      </div>
      <div className="overflow-auto rounded border border-neutral-800 bg-black p-2">
        <canvas ref={canvasRef} width={768} height={768} className="block w-full h-auto" />
      </div>
    </div>
  )
}
